// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: segcha.proto

package segchaproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateChallengeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumSteps uint32 `protobuf:"varint,1,opt,name=num_steps,json=numSteps,proto3" json:"num_steps,omitempty"`
}

func (x *GenerateChallengeRequest) Reset() {
	*x = GenerateChallengeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segcha_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateChallengeRequest) ProtoMessage() {}

func (x *GenerateChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_segcha_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateChallengeRequest.ProtoReflect.Descriptor instead.
func (*GenerateChallengeRequest) Descriptor() ([]byte, []int) {
	return file_segcha_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateChallengeRequest) GetNumSteps() uint32 {
	if x != nil {
		return x.NumSteps
	}
	return 0
}

type Challenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pictures [][]byte `protobuf:"bytes,2,rep,name=pictures,proto3" json:"pictures,omitempty"`
	Answers  []uint32 `protobuf:"varint,3,rep,packed,name=answers,proto3" json:"answers,omitempty"`
}

func (x *Challenge) Reset() {
	*x = Challenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_segcha_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Challenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Challenge) ProtoMessage() {}

func (x *Challenge) ProtoReflect() protoreflect.Message {
	mi := &file_segcha_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Challenge.ProtoReflect.Descriptor instead.
func (*Challenge) Descriptor() ([]byte, []int) {
	return file_segcha_proto_rawDescGZIP(), []int{1}
}

func (x *Challenge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Challenge) GetPictures() [][]byte {
	if x != nil {
		return x.Pictures
	}
	return nil
}

func (x *Challenge) GetAnswers() []uint32 {
	if x != nil {
		return x.Answers
	}
	return nil
}

var File_segcha_proto protoreflect.FileDescriptor

var file_segcha_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x67, 0x63, 0x68, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x73, 0x65, 0x67, 0x63, 0x68, 0x61, 0x22, 0x37, 0x0a, 0x18, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x75, 0x6d, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x53, 0x74, 0x65, 0x70, 0x73, 0x22,
	0x51, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x08,
	0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x73, 0x32, 0x54, 0x0a, 0x06, 0x53, 0x65, 0x67, 0x63, 0x68, 0x61, 0x12, 0x4a, 0x0a, 0x11,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67,
	0x65, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x67, 0x63, 0x68, 0x61, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x73, 0x65, 0x67, 0x63, 0x68, 0x61, 0x2e, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x22, 0x00, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6e, 0x79, 0x69, 0x6d, 0x2f, 0x6a, 0x75, 0x6e,
	0x67, 0x6c, 0x65, 0x74, 0x76, 0x2f, 0x73, 0x65, 0x67, 0x63, 0x68, 0x61, 0x2f, 0x73, 0x65, 0x67,
	0x63, 0x68, 0x61, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_segcha_proto_rawDescOnce sync.Once
	file_segcha_proto_rawDescData = file_segcha_proto_rawDesc
)

func file_segcha_proto_rawDescGZIP() []byte {
	file_segcha_proto_rawDescOnce.Do(func() {
		file_segcha_proto_rawDescData = protoimpl.X.CompressGZIP(file_segcha_proto_rawDescData)
	})
	return file_segcha_proto_rawDescData
}

var file_segcha_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_segcha_proto_goTypes = []interface{}{
	(*GenerateChallengeRequest)(nil), // 0: segcha.GenerateChallengeRequest
	(*Challenge)(nil),                // 1: segcha.Challenge
}
var file_segcha_proto_depIdxs = []int32{
	0, // 0: segcha.Segcha.GenerateChallenge:input_type -> segcha.GenerateChallengeRequest
	1, // 1: segcha.Segcha.GenerateChallenge:output_type -> segcha.Challenge
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_segcha_proto_init() }
func file_segcha_proto_init() {
	if File_segcha_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_segcha_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateChallengeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_segcha_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Challenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_segcha_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_segcha_proto_goTypes,
		DependencyIndexes: file_segcha_proto_depIdxs,
		MessageInfos:      file_segcha_proto_msgTypes,
	}.Build()
	File_segcha_proto = out.File
	file_segcha_proto_rawDesc = nil
	file_segcha_proto_goTypes = nil
	file_segcha_proto_depIdxs = nil
}
