// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: application_runtime.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveApplicationPageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	PageId        string `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
}

func (x *ResolveApplicationPageRequest) Reset() {
	*x = ResolveApplicationPageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveApplicationPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveApplicationPageRequest) ProtoMessage() {}

func (x *ResolveApplicationPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveApplicationPageRequest.ProtoReflect.Descriptor instead.
func (*ResolveApplicationPageRequest) Descriptor() ([]byte, []int) {
	return file_application_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveApplicationPageRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ResolveApplicationPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type ResolveApplicationPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationFileName string                 `protobuf:"bytes,1,opt,name=application_file_name,json=applicationFileName,proto3" json:"application_file_name,omitempty"`
	PageTitle           string                 `protobuf:"bytes,2,opt,name=page_title,json=pageTitle,proto3" json:"page_title,omitempty"`
	ApplicationVersion  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=application_version,json=applicationVersion,proto3" json:"application_version,omitempty"`
}

func (x *ResolveApplicationPageResponse) Reset() {
	*x = ResolveApplicationPageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_application_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveApplicationPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveApplicationPageResponse) ProtoMessage() {}

func (x *ResolveApplicationPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveApplicationPageResponse.ProtoReflect.Descriptor instead.
func (*ResolveApplicationPageResponse) Descriptor() ([]byte, []int) {
	return file_application_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveApplicationPageResponse) GetApplicationFileName() string {
	if x != nil {
		return x.ApplicationFileName
	}
	return ""
}

func (x *ResolveApplicationPageResponse) GetPageTitle() string {
	if x != nil {
		return x.PageTitle
	}
	return ""
}

func (x *ResolveApplicationPageResponse) GetApplicationVersion() *timestamppb.Timestamp {
	if x != nil {
		return x.ApplicationVersion
	}
	return nil
}

var File_application_runtime_proto protoreflect.FileDescriptor

var file_application_runtime_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6a, 0x75, 0x6e,
	0x67, 0x6c, 0x65, 0x74, 0x76, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x1d, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76,
	0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0xc0, 0x01, 0x0a, 0x1e, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x70,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x4b, 0x0a,
	0x13, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x12, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6e, 0x79, 0x69, 0x6d, 0x2f, 0x6a,
	0x75, 0x6e, 0x67, 0x6c, 0x65, 0x74, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_application_runtime_proto_rawDescOnce sync.Once
	file_application_runtime_proto_rawDescData = file_application_runtime_proto_rawDesc
)

func file_application_runtime_proto_rawDescGZIP() []byte {
	file_application_runtime_proto_rawDescOnce.Do(func() {
		file_application_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_application_runtime_proto_rawDescData)
	})
	return file_application_runtime_proto_rawDescData
}

var file_application_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_application_runtime_proto_goTypes = []interface{}{
	(*ResolveApplicationPageRequest)(nil),  // 0: jungletv.ResolveApplicationPageRequest
	(*ResolveApplicationPageResponse)(nil), // 1: jungletv.ResolveApplicationPageResponse
	(*timestamppb.Timestamp)(nil),          // 2: google.protobuf.Timestamp
}
var file_application_runtime_proto_depIdxs = []int32{
	2, // 0: jungletv.ResolveApplicationPageResponse.application_version:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_application_runtime_proto_init() }
func file_application_runtime_proto_init() {
	if File_application_runtime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_application_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveApplicationPageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_application_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveApplicationPageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_application_runtime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_runtime_proto_goTypes,
		DependencyIndexes: file_application_runtime_proto_depIdxs,
		MessageInfos:      file_application_runtime_proto_msgTypes,
	}.Build()
	File_application_runtime_proto = out.File
	file_application_runtime_proto_rawDesc = nil
	file_application_runtime_proto_goTypes = nil
	file_application_runtime_proto_depIdxs = nil
}
